config/routes.rb
Rails.application.routes.draw do
  
  root "flights#index"
  get "flights" => "flights#index"
  resources :bookings, only:[:new, :create, :show]

end

app/models/airport.rb
class Airport < ActiveRecord::Base

  has_many :departing_flights, :class_name => "Flight", :foreign_key => :from_airport_id
  has_many :arriving_flights, :class_name => "Flight", :foreign_key => :to_airport_id

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  
  belongs_to :from_airport, :class_name => "Airport"
  belongs_to :to_airport,   :class_name => "Airport"
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking

  validates_presence_of :name
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:booking][:flight_id])
    params[:num_tickets].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    respond_to do |format|
      if @booking.save
        flash[:success] = "The flight has been successfully booked."
        @booking.passengers.each { |passenger| PassengerMailer.booking_email(passenger).deliver_now }
        format.html {redirect_to @booking }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  def index
    @flight = Flight.new
    @airports = Airport.all.map { |airport| [airport.code + " - " + airport.name, airport.id] }
    @dates = Flight.order("datetime").all.map { |flight| flight.datetime.strftime("%d-%m-%Y") }.uniq

    if !params[:flight].nil?
      search
      @booking = Booking.new
    end

  end

  def search
    selected_date = Date.parse(params[:flight][:datetime])
    @flights = Flight.where(from_airport_id: params[:flight][:from_airport],
                           to_airport_id:   params[:flight][:to_airport],
                           datetime:        selected_date.beginning_of_day..selected_date.end_of_day)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/create.js.erb
<% if @booking.save %>

  window.setTimeout(function() {
      window.location.href = "<%= booking_path(@booking) %>";
  }, 1000);

<% else %>

  $('#errors-container').html("<%= j render 'shared/error_messages', object: @booking %>");

  $('html,body').animate({
      scrollTop: $("#errors-container").offset().top
  });

<% end %>

app/views/bookings/new.html.erb
<div class="container">
  <h1>Booking</h1>
  <table class="table-fill">
    <thead>
      <tr>
        <th>Flight Number</th>
        <th>Date</th>
        <th>Time</th>
        <th>Departure</th>
        <th>Destination</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @flight.number %></td>
        <td><%= @flight.datetime.strftime("%d/%m/%Y") %></td>
        <td><%= @flight.datetime.strftime("%H:%M") %></td>
        <td><%= @flight.from_airport.code %> - <%= @flight.from_airport.name %></td>
        <td><%= @flight.to_airport.code %> - <%= @flight.to_airport.name %></td>
        <td>$ <%= @flight.price %></td>
      </tr>      
    </tbody>
  </table>
  <div id="errors-container"></div>
  <div id="passengers-form">
    <%= form_for @booking, remote: true do |f| %>
      <% @count = 0 %>
      <%= f.fields_for :passengers do |passenger_form| %>
        <div class="passenger">
          <h2>Passenger <%= @count += 1 %></h2>
          <%= passenger_form.label :name %>
          <%= passenger_form.text_field :name %>

          <%= passenger_form.label :email %>
          <%= passenger_form.email_field :email %>
        </div>
      <% end %>
      <%= f.hidden_field :flight_id, value: @flight.id %>
      <%= f.submit "Confirm booking", class: "btn booking-btn" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Booking reference: <%= @booking.id %></h1>
  <table class="table-fill">
    <thead>
      <tr>
        <th>Flight Number</th>
        <th>Date</th>
        <th>Time</th>
        <th>Departure</th>
        <th>Destination</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @booking.flight.number %></td>
        <td><%= @booking.flight.datetime.strftime("%d/%m/%Y") %></td>
        <td><%= @booking.flight.datetime.strftime("%H:%M") %></td>
        <td><%= @booking.flight.from_airport.code %> - <%= @booking.flight.from_airport.name %></td>
        <td><%= @booking.flight.to_airport.code %> - <%= @booking.flight.to_airport.name %></td>
        <td>$ <%= @booking.flight.price %></td>
      </tr>      
    </tbody>
  </table>
  <div class="passengers-container">
    <% @count = 0 %>
    <% @booking.passengers.each do |passenger| %> 
      <div class="passenger">
        <h2>Passenger <%= @count += 1 %></h2>
        <p><%= passenger.name %></p>
        <p><%= passenger.email %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/flights/_results_form.html.erb
<div class="container">
  <% if !@flights.nil? && !@flights.empty? %>
    <h1 id ="flights-title">Flights</h1>
    <%= form_for(@booking, url: new_booking_path, method: :get) do |f| %>
      <table class="table-fill">
        <thead>
          <tr>
            <th></th>
            <th>Flight Number</th>
            <th>Date</th>
            <th>Time</th>
            <th>Departure</th>
            <th>Destination</th>
            <th>Passengers</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @flights.each do |flight| %>
            <tr>
              <td><%= f.radio_button :flight_id, flight.id, :checked => (flight == @flights.first) %></td>
              <td><%= flight.number %></td>
              <td><%= flight.datetime.strftime("%d/%m/%Y") %></td>
              <td><%= flight.datetime.strftime("%H:%M") %></td>
              <td><%= flight.from_airport.code %> - <%= flight.from_airport.name %></td>
              <td><%= flight.to_airport.code %> - <%= flight.to_airport.name %></td>
              <td><%= params[:flight][:num_tickets] %></td>
              <td>$ <%= flight.price %></td>
            </tr>      
          <% end %>
        </tbody>
      </table>
        <%= hidden_field_tag :num_tickets, params[:flight][:num_tickets] %>
        <%= f.submit "Book flight", id: "confirm-btn", class: "btn" %>
    <% end %>
  <% end %>
</div>

app/views/flights/index.html.erb
<div class="index-container">
  <div class="search-panel">
    <h1>Search Flights</h1>
    <%= form_for(@flight, method: :get, remote: true) do |f| %> 

      <div>
        <div class="label-select">
          <%= f.label(:from_airport) %>
          <%= f.select(:from_airport, @airports) %>
        </div>
        <div class="label-select">
          <%= f.label(:to_airport) %>
          <%= f.select(:to_airport, @airports) %>
        </div>
      </div>

      <div class="label-select">
        <%= f.label("Date") %>
        <%= f.select(:datetime, @dates) %>
      </div>
      <div class="label-select">
        <%= f.label("Passengers") %> 
        <%= f.select(:num_tickets, 1..4) %>
      </div>

      <%= f.submit "Search", id: "search-btn", class: "btn" %>
    <% end %>
  </div>
</div>

<div id ="result">

</div>

<script type="text/javascript">
    $('#search-btn').click(function () {
        $from = $('#flight_from_airport option:selected').text();
        $to = $('#flight_to_airport option:selected').text();
        if ($from == $to) {
            alert("The origin and destination must be different.");
        }
    });
</script>

app/views/flights/index.js.erb
$("#result").html("<%= escape_javascript(render('results_form')) %>").fadeIn(600);
$('html, body').animate({ scrollTop: $("#flights-title").offset().top }, 1200);

app/views/layouts/_footer.html.erb
<footer>
  <p>Developed by Fabricio Carrara&nbsp&nbsp
    <%= link_to image_tag("github-mark.png", class: "github-mark"), "https://github.com/fcarrara/flight-booker" , target: "_blank" %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1><%= link_to image_tag("logo-white.png", class: "logo"), root_path %></h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'logo.ico' %>
</head>
<body>
  <%= render "layouts/header" %>
  <%= yield %>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>